/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Presentation {
  get author(): string
  set author(author: string)
  get origin(): string
  set origin(value: string)
  get collaborative(): boolean
  get clientId(): number
  snapshot(): any
  get slideCount(): number
  get slideIds(): Array<string>
  get widthEmu(): number
  get heightEmu(): number
  slide(slide: number): any
  story(storyId: string): any
  layouts(): any
  media(): Array<MediaResource>
  insertSlide(index: number, layout?: string | undefined | null): any
  deleteSlide(slideId: string): any
  moveSlide(slideId: string, index: number): any
  setSlideNotes(slideId: string, text: string): void
  addTextBox(slideId: string, draft: any): any
  addShape(slideId: string, draft: any): any
  removeShape(slideId: string, shapeId: string): any
  setShapeFill(slideId: string, shapeId: string, color?: string | undefined | null): any
  setShapeStroke(slideId: string, shapeId: string, stroke: any): any
  setShapeAdjust(slideId: string, shapeId: string, adjustments: any): any
  moveShape(slideId: string, shapeId: string, x: number, y: number): any
  resizeShape(slideId: string, shapeId: string, width: number, height: number): any
  setShapeRect(slideId: string, shapeId: string, rect: any): any
  insertText(storyId: string, index: number, text: string, style?: any | undefined | null): any
  deleteText(storyId: string, start: number, end: number): any
  formatText(storyId: string, start: number, end: number, patch: any): any
  setParagraphAlignment(storyId: string, start: number, end: number, alignment?: string | undefined | null): any
  insertParagraphBreak(storyId: string, index: number): any
  deleteParagraphBreak(storyId: string, index: number): any
  addComment(comment: CommentInput): any
  replyToComment(reply: CommentReplyInput): any
  setCommentStatus(commentId: string, resolved?: boolean | undefined | null): any
  removeComment(commentId: string): any
  get comments(): any
  get commentFlavor(): string
  setCommentFlavor(flavor: string): string
  registerFont(face: FontFace): number
  renderSlide(slide: number, options?: RenderSlideOptions | undefined | null): Promise<RenderedSlide>
  encodeStateVector(): Buffer
  encodeStateAsUpdate(): Buffer
  encodeDiff(stateVector: Buffer): Buffer
  applyUpdate(update: Buffer): any
  propose(request: any): any
  get proposals(): any
  previewProposal(proposalId: string): any
  acceptProposal(proposalId: string, force?: boolean | undefined | null): any
  rejectProposal(proposalId: string): boolean
  get canUndo(): boolean
  get canRedo(): boolean
  undo(): boolean
  redo(): boolean
  addUndoBarrier(): void
  save(): Promise<Buffer>
}
export type PptxPresentation = Presentation

export interface CommentInput {
  slideId: string
  text: string
  author: string
  initials?: string
  created: string
  x?: number
  y?: number
}

export interface CommentReplyInput {
  commentId: string
  text: string
  author: string
  initials?: string
  created: string
}

export interface FontFace {
  family: string
  data: Buffer
  bold?: boolean
  italic?: boolean
}

export interface MediaResource {
  path: string
  contentType: string
  data: Buffer
}

export declare function openPresentation(data: Buffer, options?: OpenPresentationOptions | undefined | null): Promise<Presentation>

export interface OpenPresentationOptions {
  clientId?: number
  author?: string
  origin?: string
}

export interface RenderedSlide {
  data: Buffer
  width: number
  height: number
  skippedImages: number
}

export interface RenderSlideOptions {
  scale?: number
  transparent?: boolean
  background?: string
  maxShadowPixels?: number
}
