/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Workbook {
  get clientId(): number
  get collaborative(): boolean
  get sheetCount(): number
  get activeSheet(): number
  set activeSheet(sheet: number)
  sheetInfo(): SheetInfo
  cell(sheet: number, address: string): CellValue
  value(sheet: number, address: string): CellComputedValue
  formula(sheet: number, address: string): string | null
  range(sheet: number, range: string): Array<Array<CellValue>>
  set(sheet: number, address: string, input: string, nowSerial?: number | undefined | null): MutationResult
  setMany(sheet: number, edits: Array<CellInput>, nowSerial?: number | undefined | null): MutationResult
  recalculate(nowSerial?: number | undefined | null): CalculationResult
  get history(): HistoryState
  get canUndo(): boolean
  get canRedo(): boolean
  undo(nowSerial?: number | undefined | null): MutationResult
  redo(nowSerial?: number | undefined | null): MutationResult
  encodeStateVector(): Buffer
  encodeStateAsUpdate(): Buffer
  encodeDiff(stateVector: Buffer): Buffer
  applyUpdate(update: Buffer, nowSerial?: number | undefined | null): CalculationResult
  propose(proposal: ProposalInput, nowSerial?: number | undefined | null): Proposal
  get proposals(): Array<Proposal>
  acceptProposal(proposalId: string, force?: boolean | undefined | null, nowSerial?: number | undefined | null): MutationResult
  rejectProposal(proposalId: string): boolean
  mergedRanges(sheet: number, range: string): Array<string>
  get lastCalculation(): CalculationResult
  setNumberFormat(sheet: number, range: string, format: string, nowSerial?: number | undefined | null): MutationResult
  setStyle(sheet: number, range: string, style: StyleInput, nowSerial?: number | undefined | null): MutationResult
  renderSheet(options?: RenderSheetOptions | undefined | null): Promise<RenderedSheet>
  save(): Promise<Buffer>
}
export type XlsxWorkbook = Workbook

export interface CalculationResult {
  changed: Array<string>
  cycleCells: Array<string>
  limitedCells: Array<string>
}

export interface CellComputedValue {
  kind: string
  number?: number
  text?: string
  boolean?: boolean
  error?: string
}

export interface CellInput {
  address: string
  input: string
}

export interface CellValue {
  address: string
  input: string
  formula: boolean
}

export interface HistoryState {
  canUndo: boolean
  canRedo: boolean
  undoDepth: number
  redoDepth: number
}

export interface MutationResult {
  applied: boolean
  changed: Array<string>
  cycleCells: Array<string>
  limitedCells: Array<string>
}

export declare function openWorkbook(data: Buffer, options?: OpenWorkbookOptions | undefined | null): Promise<Workbook>

export interface OpenWorkbookOptions {
  clientId?: number
  readOnly?: boolean
  recalculate?: boolean
  nowSerial?: number
}

export interface Proposal {
  id: string
  agentId: string
  note?: string
  edits: Array<ProposedCell>
}

export interface ProposalCellInput {
  sheet: number
  address: string
  input: string
}

export interface ProposalInput {
  agentId: string
  note?: string
  edits: Array<ProposalCellInput>
}

export interface ProposedCell {
  sheet: number
  address: string
  input: string
  before: string
  after: string
}

export interface RenderedSheet {
  data: Buffer
  width: number
  height: number
}

export interface RenderSheetOptions {
  sheet?: number
  range?: string
  scale?: number
  maxWidth?: number
  maxHeight?: number
}

export interface SheetInfo {
  ids: Array<string>
  names: Array<string>
  activeSheet: number
  contentWidth: number
  contentHeight: number
  frozenRows: number
  frozenColumns: number
  initialScrollX: number
  initialScrollY: number
}

export interface StyleInput {
  bold?: boolean
  italic?: boolean
  strikethrough?: boolean
  fontFamily?: string
  fontSize?: number
  textColor?: string
  fillColor?: string
  horizontalAlignment?: string
  verticalAlignment?: string
  textWrapping?: string
}
